# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'ZJRoutes_Example' do
  pod 'ZJRoutes', :path => '../'

  target 'ZJRoutes_Tests' do
    inherit! :search_paths

    
  end
end
